# Author:  James Buckett
# eMail: james.buckett@gmail.com
# Loki values for Helm install

loki:
  enabled: true
  persistence.enabled: true
  persistence.storageClassName: standard
  persistence.size: 5Gi

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true
  # Deploy default dashboards. These are loaded using the sidecar
  defaultDashboardsEnabled: true
  sidecar:
    datasources:
      enabled: true
  service:
    ### Contour Testing ###
    ### Added line below from type: LoadBalancer to ClusterIP
    #type: LoadBalancer
    type: ClusterIP

prometheus:
  enabled: true
  alertmanager.persistentVolume.enabled: false
  server.persistentVolume.enabled: false
