apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-istio
  namespace: ns-istio-sample
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: ing-istio-secret
      hosts:
        - istio.jamesbuckett.com
  rules:
    - host: istio.jamesbuckett.com
      http:
        paths:
          - backend:
              serviceName: productpage
              servicePort: 9080
