apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-argo
  namespace: ns-argo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: ing-argo-secret
      hosts:
        - argo.jamesbuckett.com
  rules:
    - host: argo.jamesbuckett.com
      http:
        paths:
          - backend:
              serviceName: argo-server
              servicePort: 2746
            # path: /argo(/|$)(.*)
