apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-vpa
  namespace: ns-goldilocks
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: ing-vpa-secret
      hosts:
        - vpa.jamesbuckett.com
  rules:
    - host: vpa.jamesbuckett.com
      http:
        paths:
          - backend:
              serviceName: goldilocks-release-dashboard
              servicePort: 80
